import { Question, School } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 1,
    question: "새로운 프로젝트를 시작할 때, 가장 먼저 하는 행동은?",
    options: [
      { text: "스케치북을 펼치고 감정에 이끌려 자유롭게 그림을 그린다.", traits: ['fine_art', 'conceptual'] },
      { text: "시장 트렌드와 사용자 니즈를 먼저 철저히 조사한다.", traits: ['commercial', 'design'] },
      { text: "새로운 재료나 실험해볼 최신 소프트웨어를 찾아본다.", traits: ['tech', 'fashion'] },
      { text: "작품을 관통하는 강렬한 컨셉이나 메시지를 글로 적는다.", traits: ['conceptual', 'fine_art'] },
    ],
  },
  {
    id: 2,
    question: "가장 영감을 많이 받는 장소는?",
    options: [
      { text: "화려한 광고판과 사람들로 붐비는 도심 한복판.", traits: ['commercial', 'fashion'] },
      { text: "추상화를 감상하며 깊은 사색에 잠길 수 있는 조용한 미술관.", traits: ['fine_art', 'conceptual'] },
      { text: "3D 프린터와 코드로 가득 찬 최첨단 테크 랩.", traits: ['tech', 'design'] },
      { text: "동료들과 서로의 작업물을 치열하게 피드백하는 스튜디오.", traits: ['design', 'commercial'] },
    ],
  },
  {
    id: 3,
    question: "나의 최종적인 커리어 목표는?",
    options: [
      { text: "전 세계 갤러리에 작품을 전시하는 유명 아티스트.", traits: ['fine_art'] },
      { text: "탑티어 에이전시 취업 혹은 나만의 글로벌 브랜드 런칭.", traits: ['commercial', 'fashion'] },
      { text: "디자인을 통해 복잡한 사회/기술적 문제를 해결하는 것.", traits: ['design', 'tech'] },
      { text: "기존의 사회적 통념을 깨부수고 사람들에게 충격을 주는 것.", traits: ['conceptual'] },
    ],
  },
  {
    id: 4,
    question: "어떤 수업 방식이 더 흥미로운가?",
    options: [
      { text: "기초부터 탄탄하게 다지는 실기 훈련과 스킬 업그레이드.", traits: ['commercial', 'design'] },
      { text: "정해진 답 없이 끊임없이 질문하고 토론하는 이론 수업.", traits: ['conceptual', 'fine_art'] },
      { text: "최신 디지털 툴과 코딩을 활용해 새로운 것을 만드는 수업.", traits: ['tech'] },
      { text: "패션의 역사와 트렌드를 분석하고 미래를 예측하는 수업.", traits: ['fashion'] },
    ],
  },
  {
    id: 5,
    question: "자신을 가장 잘 표현하는 키워드는?",
    options: [
      { text: "혁신 (Innovation)", traits: ['tech', 'design'] },
      { text: "표현 (Expression)", traits: ['fine_art'] },
      { text: "전략 (Strategy)", traits: ['commercial'] },
      { text: "아방가르드 (Avant-garde)", traits: ['fashion', 'conceptual'] },
    ],
  },
];

export const SCHOOLS: School[] = [
  {
    id: 'sva',
    name: 'School of Visual Arts',
    shortName: 'SVA',
    location: '미국 뉴욕',
    description: '실무 중심 교육의 최강자. 그래픽 디자인, 일러스트레이션, 광고 분야에서 압도적인 취업률과 네트워크를 자랑합니다. "Dream Big"을 실현하는 곳.',
    tags: ['design', 'commercial'],
    color: 'bg-blue-600',
    textColor: 'text-blue-600',
    bgAccent: 'bg-blue-50',
  },
  {
    id: 'mica',
    name: 'Maryland Institute College of Art',
    shortName: 'MICA',
    location: '미국 볼티모어',
    description: '순수 미술과 교육의 전통 강호. 자유롭고 실험적인 분위기 속에서 개인의 예술적 비전을 깊이 있게 탐구할 수 있습니다.',
    tags: ['fine_art', 'conceptual'],
    color: 'bg-teal-600',
    textColor: 'text-teal-600',
    bgAccent: 'bg-teal-50',
  },
  {
    id: 'scad',
    name: 'Savannah College of Art and Design',
    shortName: 'SCAD',
    location: '미국 사바나/애틀랜타',
    description: '엔터테인먼트와 테크놀로지의 결합. 모션 그래픽, 3D 애니메이션, 게임 디자인 등 상업 예술 분야에서 최고의 시설과 지원을 제공합니다.',
    tags: ['tech', 'commercial'],
    color: 'bg-yellow-500',
    textColor: 'text-yellow-600',
    bgAccent: 'bg-yellow-50',
  },
  {
    id: 'fit',
    name: 'Fashion Institute of Technology',
    shortName: 'FIT',
    location: '미국 뉴욕',
    description: '패션 비즈니스와 디자인의 메카. 뉴욕 주립대로 합리적인 학비와 강력한 산업 연계성을 자랑하며, 바로 현장에 투입 가능한 인재를 기릅니다.',
    tags: ['fashion', 'commercial'],
    color: 'bg-cyan-600',
    textColor: 'text-cyan-600',
    bgAccent: 'bg-cyan-50',
  },
  {
    id: 'risd',
    name: 'Rhode Island School of Design',
    shortName: 'RISD',
    location: '미국 프로비던스',
    description: "'미대 입시의 하버드'. 엄격한 커리큘럼과 뛰어난 교수진을 바탕으로 파인 아트와 디자인 전 분야에서 최고 수준의 교육을 제공합니다.",
    tags: ['fine_art', 'design'],
    color: 'bg-indigo-600',
    textColor: 'text-indigo-600',
    bgAccent: 'bg-indigo-50',
  },
  {
    id: 'parsons',
    name: 'Parsons School of Design',
    shortName: 'Parsons',
    location: '미국 뉴욕',
    description: '세계 패션 트렌드의 중심. 창의성과 상업성의 조화를 중시하며, 수많은 유명 디자이너를 배출한 명문 디자인 스쿨입니다.',
    tags: ['fashion', 'design'],
    color: 'bg-red-600',
    textColor: 'text-red-600',
    bgAccent: 'bg-red-50',
  },
  {
    id: 'artcenter',
    name: 'ArtCenter College of Design',
    shortName: 'ArtCenter',
    location: '미국 패서디나',
    description: '산업 디자인과 컨셉 아트의 성지. 실무보다 더 실무 같은 강도 높은 교육으로 졸업 후 즉시 활약할 수 있는 프로를 양성합니다.',
    tags: ['design', 'tech'],
    color: 'bg-orange-600',
    textColor: 'text-orange-600',
    bgAccent: 'bg-orange-50',
  },
  {
    id: 'ual',
    name: 'University of the Arts London',
    shortName: 'UAL',
    location: '영국 런던',
    description: 'CSM, LCC, Chelsea 등 6개 명문 대학의 연합체. 실험적이고 전위적인 예술부터 실용적인 디자인까지, 런던 예술의 중심입니다.',
    tags: ['conceptual', 'fashion'],
    color: 'bg-pink-600',
    textColor: 'text-pink-600',
    bgAccent: 'bg-pink-50',
  },
  {
    id: 'csvpa',
    name: 'Cambridge School of Visual & Performing Arts',
    shortName: 'CSVPA',
    location: '영국 케임브리지',
    description: '개인 맞춤형 소수 정예 교육. 학생 개개인의 잠재력을 극대화하는 파운데이션 과정이 유명하며, 세심한 케어를 받을 수 있습니다.',
    tags: ['fine_art', 'design'],
    color: 'bg-green-600',
    textColor: 'text-green-600',
    bgAccent: 'bg-green-50',
  },
];